image: golang:1.14

stages:
  - test
  - build
  - image

test:
  stage: test
  script:
    - go test -v ./...

build:
  stage: build
  variables: 
    CGO_ENABLED: 0
  artifacts: 
    - ./out
  script:
    - go build -o out/semantic-release ./cmd/semantic-release/
    - ./semantic-release -dry || true

image:
  stage: image
  tags:
    - docker
  cache: {}
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    REGISTRY_IMAGE: registry.gitlab.com/go-semantic-release/semantic-release
  services:
    - docker:dind
  dependencies: 
    - build
  only:
    - tags 
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --tag $REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $REGISTRY_IMAGE/web/server:$CI_COMMIT_TAG
