language: go
go:
  - 1.12.x
env:
- GO111MODULE=on
install:
  - nvm install 10
  - node -v && npm -v
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
before_script:
  - go build ./cmd/semantic-release/
after_success:
  - ./scripts/release
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
