name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup PATH
        run: echo "::add-path::~/go/bin"

      - name: Get dependencies
        run: |
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
          go get -v -t -d ./...

      - name: Build
        run: go build ./cmd/semantic-release/

      - name: Test
        run: go test -v ./...

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/release || exit 0
